jobs:
  include:
    - os: windows
      language: bash
      install:
        - choco install dotnetcore-sdk
        - choco install opencover.portable
        - dotnet --version
      script: 
        - dotnet restore -s https://api.nuget.org/v3/index.json
        - dotnet build
        - dotnet test
        - OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test" -output:coverage.xml -filter:"+[*]* -[*Moq]* -[xunit*]*" -oldstyle
        - curl -s https://codecov.io/bash > codecov
        - chmod +x codecov
        - ./codecov -f "coverage.xml"
    - os: linux
      dist: xenial
      language: csharp
      mono: none
      sudo: required
      install:
        - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo apt-get install apt-transport-https
        - sudo apt-get update
        - sudo apt-get install dotnet-sdk-2.2
        - dotnet --version
      script:
        - dotnet build
        - dotnet test
    - stage: Docker
      os: linux
      dist: xenial
      language: csharp
      mono: none
      sudo: required
      services:
        docker
      script:
        - docker-compose build
        - docker-compose up -d
        - curl http://localhost:8085
        - docker-compose stop
        - docker-compose logs