version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./docker/frontend/client/Dockerfile
    image: mindnote:client
  # host:
    # build:
      # context: .
      # dockerfile: ./docker/frontend/host/Dockerfile
    # image: mindnote:host
  api:
    build:
      context: .
      dockerfile: ./docker/backend/api/Dockerfile
    image: mindnote:api
  identity:
    build:
      context: .
      dockerfile: ./docker/backend/identity/Dockerfile
    image: mindnote:identity