version: "3"
services:
  host:
    build:
      context: .
      dockerfile: ./docker/host/Dockerfile
    image: mindnote:host
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: mindnote:api
  identity:
    build:
      context: .
      dockerfile: ./docker/identity/Dockerfile
    image: mindnote:identity