version: "3"
services:
  proxy:
    image: nginx
    depends_on:
      - host
      - identity
      - api
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9050:80"
  host:
    build:
      context: .
      dockerfile: ./docker/host/Dockerfile
    environment:
      - API_SERVER=http://api
      - IDENTITY_SERVER=http://identity
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
      - identity
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - ConnectionString=server=mndb;userid=root;pwd=MNdb_passw00d;port=3306;database=mndb;
      - DBType=MySQL
      - ASPNETCORE_ENVIRONMENT=Development
      - IDENTITY_SERVER=http://identity
    depends_on:
      - mndb
      - identity
  identity:
    build:
      context: .
      dockerfile: ./docker/identity/Dockerfile
    environment:
      - ConnectionString=server=mndb;userid=root;pwd=MNdb_passw00d;port=3306;database=mniddb;
      - DBType=MySQL
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mndb
  mndb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MNdb_passw00d