version: "3"
services:
  host:
    build:
      context: .
      dockerfile: ./docker/host/Dockerfile
    environment:
      - API_SERVER=http://api:3000
      - IDENTITY_SERVER=http://identity:3050
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"
    depends_on:
      - api
      - identity
  identity:
    build:
      context: .
      dockerfile: ./docker/identity/Dockerfile
    environment:
      - ConnectionString=server=mndb;userid=root;pwd=MNdb_passw00d;port=3306;database=mniddb;
      - DBType=MySQL
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:3050
    ports:
      - "8050:3050"
    depends_on:
      - mndb
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - ConnectionString=server=mndb;userid=root;pwd=MNdb_passw00d;port=3306;database=mndb;
      - DBType=MySQL
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:3000
    ports:
      - "8000:3000"
    depends_on:
      - mndb
  mndb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MNdb_passw00d