version: "3"
services:
  host:
    build:
      context: .
      dockerfile: ./docker/host/Dockerfile
    environment:
      # - ConnectionString=Server=mndb;Database=master;User=sa;Password=MNdb_passw00d;
      - API_SERVER=https://api:5123
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8085:80"
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      # - ConnectionString=Server=mndb;Database=master;User=sa;Password=MNdb_passw00d;
      - ConnectionString=server=mndb;userid=root;pwd=MNdb_passw00d;port=3306;database=mndb;
      - DBType=MySQL
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="https://*:5123"
    depends_on:
      - mndb
  mndb:
    image: mysql
    # ports:
      # - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=MNdb_passw00d
  #   image: "mcr.microsoft.com/mssql/server"
  #   environment:
  #     - SA_PASSWORD=MNdb_passw00d
  #     - ACCEPT_EULA=Y