version: "3"
services:
  host:
    build:
      context: .
      dockerfile: ./docker/host/Dockerfile
    image: mindnote:host
    environment:
      - API_SERVER=http://localhost:8050
      - IDENTITY_SERVER=http://localhost:8000
      - PATH_BASE=/
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8100
    network_mode: "host"
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: mindnote:api
    environment:
      - ConnectionString=server=localhost;userid=root;pwd=MNdb_passw00d;port=3306;database=mndb;
      - DBType=MySQL
      - ASPNETCORE_ENVIRONMENT=Development
      - PATH_BASE=/
      - IDENTITY_SERVER=http://localhost:8000
      - ASPNETCORE_URLS=http://*:8050
    depends_on:
      - mndb
    network_mode: "host"
  identity:
    build:
      context: .
      dockerfile: ./docker/identity/Dockerfile
    image: mindnote:identity
    environment:
      - ConnectionString=server=localhost;userid=root;pwd=MNdb_passw00d;port=3306;database=mniddb;
      - DBType=MySQL
      - ASPNETCORE_ENVIRONMENT=Development
      - SERVER_HOST=http://localhost:8100
      - IDENTITY_SERVER=http://localhost:8000
      - ASPNETCORE_URLS=http://*:8000
    depends_on:
      - mndb
    network_mode: "host"
  mndb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MNdb_passw00d
    ports:
      - "3306:3306"