version: "3"
services:
  host:
    image: stardustdl/mindnote:host
    environment:
      - API_SERVER=http://api:3000
      - IDENTITY_SERVER=http://identity:3050
    ports:
      - "9000:80"
    depends_on:
      - api
      - identity
  identity:
    image: stardustdl/mindnote:identity
    environment:
      - ConnectionString=server=mndb;userid=root;pwd=MNdb_passw00d;port=3306;database=mniddb;
      - DBType=MySQL
      - ASPNETCORE_URLS=http://*:3050
    ports:
      - "8050:3050"
    depends_on:
      - mndb
  api:
    image: stardustdl/mindnote:api
    environment:
      - ConnectionString=server=mndb;userid=root;pwd=MNdb_passw00d;port=3306;database=mndb;
      - DBType=MySQL
      - ASPNETCORE_URLS=http://*:3000
    ports:
      - "8000:3000"
    depends_on:
      - mndb
  mndb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MNdb_passw00d