version: "3"
services:
  host:
    image: stardustdl/mindnote:host
    environment:
      - API_SERVER=http://api:5123
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8085:80"
    depends_on:
      - api
  api:
    image: stardustdl/mindnote:api
    environment:
      - ConnectionString=server=mndb;userid=root;pwd=MNdb_passw00d;port=3306;database=mndb;
      - DBType=MySQL
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5123
    ports:
      - "5123"
    depends_on:
      - mndb
  mndb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MNdb_passw00d