version: "3"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - host
      - api
      - identity
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
  host:
    image: stardustdl/mindnote:dev-host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_SERVER=http://api.mindnote.com
      - IDENTITY_SERVER=http://id.mindnote.com
    depends_on:
      - api
    entrypoint: ["./wait-for-it.sh", "api:80", "-t", "0", "--", "dotnet", "MindNote.Server.Host.dll"]
  api:
    image: stardustdl/mindnote:dev-api
    environment:
      - ConnectionString=server=mndb;userid=root;pwd=MNdb_passw00d;port=3306;database=mndb;
      - DBType=MySQL
      - IDENTITY_SERVER=http://id.mindnote.com
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mndb
      - identity
    entrypoint: ["./wait-for-it.sh", "identity:80", "-t", "0", "--", "dotnet", "MindNote.Server.API.dll"]
  identity:
    image: stardustdl/mindnote:dev-identity
    environment:
      - ConnectionString=server=mndb;userid=root;pwd=MNdb_passw00d;port=3306;database=mniddb;
      - DBType=MySQL
      - IDENTITY_SERVER=http://id.mindnote.com
      - SERVER_HOST=http://mindnote.com
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mndb
    entrypoint: ["./wait-for-it.sh", "mndb:3306", "-t", "0", "--", "dotnet", "MindNote.Server.Identity.dll"]
  mndb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MNdb_passw00d
    volumes:
      - "./db:/var/lib/mysql"
