version: "3"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - host
      - api
      - identity
    volumes:
      - "./config/nginx_default.conf:/etc/nginx/conf.d/default.conf"
  host:
    image: stardustdl/mindnote:dev-host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    volumes:
      - "./config/server_host.json:/app/appsettings.json"
    entrypoint: ["./wait-for-it.sh", "api:80", "-t", "0", "--", "dotnet", "MindNote.Server.Host.dll"]
  api:
    image: stardustdl/mindnote:dev-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mndb
      - identity
    volumes:
      - "./config/server_api.json:/app/appsettings.json"
    entrypoint: ["./wait-for-it.sh", "identity:80", "-t", "0", "--", "dotnet", "MindNote.Server.API.dll"]
  identity:
    image: stardustdl/mindnote:dev-identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mndb
    volumes:
      - "./config/server_identity.json:/app/appsettings.json"
    entrypoint: ["./wait-for-it.sh", "mndb:3306", "-t", "0", "--", "dotnet", "MindNote.Server.Identity.dll"]
  mndb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MNdb_passw00d
    volumes:
      - "./db:/var/lib/mysql"
