version: "3"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - client
      # - host
      - api
      - identity
    volumes:
      - "./config/nginx_default.conf:/etc/nginx/conf.d/default.conf"
  client:
    image: stardustdl/mindnote:dev-client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    volumes:
      - "./config/frontend_client.json:/app/appsettings.json"
    entrypoint: ["./wait-for-it.sh", "api:80", "-t", "0", "--", "dotnet", "run", "-p", "./MindNote.Frontend.Client.Server"]
  # host:
  #   image: stardustdl/mindnote:dev-host
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   depends_on:
  #     - api
  #   volumes:
  #     - "./config/frontend_server.json:/app/appsettings.json"
  #   entrypoint: ["./wait-for-it.sh", "api:80", "-t", "0", "--", "dotnet", "MindNote.Frontend.Server.dll"]
  api:
    image: stardustdl/mindnote:dev-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mndb
      - identity
    volumes:
      - "./config/backend_api.json:/app/appsettings.json"
    entrypoint: ["./wait-for-it.sh", "identity:80", "-t", "0", "--", "dotnet", "MindNote.Backend.API.dll"]
  identity:
    image: stardustdl/mindnote:dev-identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mndb
    volumes:
      - "./config/backend_identity.json:/app/appsettings.json"
    entrypoint: ["./wait-for-it.sh", "mndb:3306", "-t", "0", "--", "dotnet", "MindNote.Backend.Identity.dll"]
  mndb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MNdb_passw00d
    volumes:
      - "./db:/var/lib/mysql"
